drop table salesman;

create table salesman (s_id number, name varchar2(20), email varchar2(20), salary number );

insert into salesman values (1, 'Safin', 'safin@ss', 12000);
insert into salesman values (2, 'Nafiz', 'Nafiz@ss', 13000);
insert into salesman values (3, 'Abdul', 'Abdul@dd', 10000);
insert into salesman values (4, 'Tushar', 'Asif@ss', 12000);
insert into salesman values (5, 'Rafat', 'Rafat@dd', 15000);	

commit;



------update,, delete kora lagbe
